### ISSUE TITLE
error code

### ISSUE THREAD

**Issue by N1kx0** [Rimmuru/Rimurus-2T1-Scripts#26]
i can execute the menu but it throws me a error code and i cnat open it
![rimuru](https://user-images.githubusercontent.com/121137388/224495953-a87656b3-ed60-4aea-bbcf-dae4adaac152.PNG)

**Comment by Rimmuru** [comment]
reinstall usually fixes it

**Comment by Rimmuru** [comment]
this is fixed in 3.2.0
